name: dbc-network
recipe: drupal9
config:
  composer_version: 2
  database: mysql
  webroot: web
services:
  appserver:
    build:
      - composer install
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://dbc-network.lndo.site"
database: drupal9
username: drupal9
password: drupal9
host: database
port: 3306
