accordion_menus:
  wiki: wiki
  admin: 0
  footer: 0
  main: 0
  tools: 0
  account: 0
accordion_menus_no_submenus:
  admin: 0
  footer: 0
  main: 0
  tools: 0
  account: 0
  wiki: 0
accordion_menus_default_closed:
  admin: 0
  footer: 0
  main: 0
  tools: 0
  account: 0
  wiki: 0
