_core:
  default_config_hash: eKR4FfUD7Cp3bXamsCz6GAxh0PCLIZNMa65y2kChIh0
site_key: 6Leam1UdAAAAANBWnhWiArJA1UkcVIIhTr0nhD4D
secret_key: none
verify_hostname: false
use_globally: true
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: false
